"""add delivery

Revision ID: 00a431cd0669
Revises: 46b8ebf5be45
Create Date: 2025-11-17 19:46:12.698663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a431cd0669'
down_revision: Union[str, Sequence[str], None] = '46b8ebf5be45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_deliveries',
    sa.Column('institution_id', sa.Integer(), nullable=False, comment='ID da instituição que realizou a entrega'),
    sa.Column('family_id', sa.Integer(), nullable=False, comment='ID da família que recebeu a entrega'),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.String(length=25), nullable=False, comment='Data e hora da entrega'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descrição da entrega realizada'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_delivery_date', 'family_deliveries', ['delivery_date'], unique=False)
    op.create_index('idx_family_delivery_family_id', 'family_deliveries', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_deliveries_account_id'), 'family_deliveries', ['account_id'], unique=False)
    op.create_index(op.f('ix_family_deliveries_family_id'), 'family_deliveries', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_deliveries_institution_id'), 'family_deliveries', ['institution_id'], unique=False)
    op.add_column('account_families', sa.Column('size', sa.Integer(), nullable=True, comment='Número de membros na família'))
    op.execute("UPDATE account_families SET size = 1 WHERE size IS NULL")
    op.alter_column('account_families', 'size', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_families', 'size')
    op.drop_index(op.f('ix_family_deliveries_institution_id'), table_name='family_deliveries')
    op.drop_index(op.f('ix_family_deliveries_family_id'), table_name='family_deliveries')
    op.drop_index(op.f('ix_family_deliveries_account_id'), table_name='family_deliveries')
    op.drop_index('idx_family_delivery_family_id', table_name='family_deliveries')
    op.drop_index('idx_family_delivery_date', table_name='family_deliveries')
    op.drop_table('family_deliveries')
    # ### end Alembic commands ###
