"""fix

Revision ID: 050f31188c2a
Revises: bad5b39e3a77
Create Date: 2025-11-22 17:26:27.209290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '050f31188c2a'
down_revision: Union[str, Sequence[str], None] = 'bad5b39e3a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome da pessoa autorizada'),
    sa.Column('cpf', sa.String(length=11), nullable=True, comment='CPF da pessoa autorizada'),
    sa.Column('kinship', sa.Enum('SON', 'SPOUSE', 'FATHER', 'MOTHER', 'OTHER', name='degreeofkinship', native_enum=False), nullable=False, comment='Relação com a família'),
    sa.Column('family_id', sa.Integer(), nullable=False, comment='Família à qual a pessoa está autorizada'),
    sa.Column('can_receive', sa.Boolean(), nullable=False, comment='Indica se a pessoa autorizada pode receber auxílios em nome da família'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_member_cpf', 'family_members', ['cpf'], unique=False)
    op.create_index('idx_family_member_family_id', 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_cpf'), 'family_members', ['cpf'], unique=True)
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.drop_index(op.f('ix_authorized_persons_families_cpf'), table_name='authorized_persons_families')
    op.drop_index(op.f('ix_authorized_persons_families_family_id'), table_name='authorized_persons_families')
    op.drop_table('authorized_persons_families')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_persons_families',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Nome da pessoa autorizada'),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=True, comment='CPF da pessoa autorizada'),
    sa.Column('kinship', sa.VARCHAR(length=6), autoincrement=False, nullable=False, comment='Relação com a família'),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Família à qual a pessoa está autorizada'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], name=op.f('authorized_persons_families_family_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('authorized_persons_families_pkey'))
    )
    op.create_index(op.f('ix_authorized_persons_families_family_id'), 'authorized_persons_families', ['family_id'], unique=False)
    op.create_index(op.f('ix_authorized_persons_families_cpf'), 'authorized_persons_families', ['cpf'], unique=True)
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_cpf'), table_name='family_members')
    op.drop_index('idx_family_member_family_id', table_name='family_members')
    op.drop_index('idx_family_member_cpf', table_name='family_members')
    op.drop_table('family_members')
    # ### end Alembic commands ###
