"""fix

Revision ID: 0bd4b223e0b5
Revises: 451b2b88d171
Create Date: 2025-11-25 15:04:59.303255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd4b223e0b5'
down_revision: Union[str, Sequence[str], None] = '451b2b88d171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_deliveries', sa.Column('delivered_at', sa.String(length=25), nullable=True, comment='Data e hora em que a entrega foi realizada'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_deliveries', 'delivered_at')
    # ### end Alembic commands ###
