"""add reference user in institutions

Revision ID: 0cfa607d2616
Revises: 60c2c66923ac
Create Date: 2025-10-07 19:53:04.651763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfa607d2616'
down_revision: Union[str, Sequence[str], None] = '60c2c66923ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'institution_id')
    # ### end Alembic commands ###
