"""fix reference user in institutions

Revision ID: 1bf5bc9f755a
Revises: 7a5baa6d80c1
Create Date: 2025-10-10 19:15:37.974433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf5bc9f755a'
down_revision: Union[str, Sequence[str], None] = '7a5baa6d80c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
