"""fix

Revision ID: 451b2b88d171
Revises: 6a9e11181433
Create Date: 2025-11-25 12:57:42.258861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451b2b88d171'
down_revision: Union[str, Sequence[str], None] = '6a9e11181433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_attempts',
    sa.Column('family_delivery_id', sa.Integer(), nullable=False, comment='ID da entrega da família'),
    sa.Column('status', sa.Enum('DELIVERED', 'NOT_DELIVERED', name='deliveryattemptstatus', native_enum=False), nullable=False, comment='Status da tentativa de entrega'),
    sa.Column('attempt_date', sa.String(length=25), nullable=False, comment='Data e hora da tentativa de entrega'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Descrição da tentativa de entrega'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_delivery_id'], ['family_deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_family_delivery_id'), 'delivery_attempts', ['family_delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_attempts_status'), 'delivery_attempts', ['status'], unique=False)
    op.add_column('family_deliveries', sa.Column('delivery_attempts', sa.Integer(), nullable=False, comment='Número de tentativas de entrega realizadas'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_deliveries', 'delivery_attempts')
    op.drop_index(op.f('ix_delivery_attempts_status'), table_name='delivery_attempts')
    op.drop_index(op.f('ix_delivery_attempts_family_delivery_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    # ### end Alembic commands ###
