"""ajuste

Revision ID: 58bb34ea4da6
Revises: 827fed87387d
Create Date: 2025-11-08 17:26:07.020524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58bb34ea4da6'
down_revision: Union[str, Sequence[str], None] = '827fed87387d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password', sa.String(length=255), nullable=False))
    op.alter_column('accounts', 'account_type',
               existing_type=postgresql.ENUM('DELIVERY_MAN', 'ADMINISTRATIVE', 'BENEFITED', 'INDEFINED', name='accounttype'),
               type_=sa.Enum('OWNER', 'DELIVERY_MAN', 'ADMINISTRATIVE', 'ASSISTANT', 'VOLUNTEER', 'UNDEFINED', name='accounttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('accounts', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('accounts_email_key'), 'accounts', type_='unique')
    op.drop_index(op.f('accounts_login_idx'), table_name='accounts')
    op.drop_constraint(op.f('accounts_login_key'), 'accounts', type_='unique')
    op.create_index('idx_accounts_email', 'accounts', ['email'], unique=False)
    op.create_index('idx_accounts_institution', 'accounts', ['institution_id'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.drop_constraint(op.f('accounts_family_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'senha')
    op.drop_column('accounts', 'login')
    op.drop_column('accounts', 'family_id')
    op.drop_constraint(op.f('families_owner_id_key'), 'families', type_='unique')
    op.drop_constraint(op.f('families_owner_id_fkey'), 'families', type_='foreignkey')
    op.drop_column('families', 'owner_id')
    op.add_column('institutions', sa.Column('institution_type', sa.Enum('ONGS', 'CHURCH', name='institutiontype', native_enum=False), nullable=False))
    op.drop_index(op.f('institutions_name_idx'), table_name='institutions')
    op.drop_constraint(op.f('institutions_owner_id_key'), 'institutions', type_='unique')
    op.create_index('idx_institutions_name', 'institutions', ['name'], unique=False)
    op.create_index('idx_institutions_type', 'institutions', ['institution_type'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.drop_constraint(op.f('institutions_owner_id_fkey'), 'institutions', type_='foreignkey')
    op.drop_column('institutions', 'owner_id')
    op.drop_column('institutions', 'institutions_type')
    op.drop_index(op.f('profiles_cpf_idx'), table_name='profiles')
    op.drop_constraint(op.f('profiles_cpf_key'), 'profiles', type_='unique')
    op.create_index('idx_profiles_account', 'profiles', ['account_id'], unique=False)
    op.create_index('idx_profiles_cpf', 'profiles', ['cpf'], unique=False)
    op.create_index(op.f('ix_profiles_cpf'), 'profiles', ['cpf'], unique=True)
    op.create_unique_constraint(None, 'profiles', ['account_id'])
    op.drop_constraint(op.f('profiles_account_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_stock_history_created', 'stock_history', ['created'], unique=False)
    op.create_index('idx_stock_history_item', 'stock_history', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_history_stock_item_id'), 'stock_history', ['stock_item_id'], unique=False)
    op.drop_constraint(op.f('stock_history_stock_item_id_fkey'), 'stock_history', type_='foreignkey')
    op.create_foreign_key(None, 'stock_history', 'stock_items', ['stock_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stock_items', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_items', 'sku',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('unique_sku_family'), table_name='stock_items')
    op.drop_index(op.f('unique_sku_institution'), table_name='stock_items')
    op.create_index('idx_stock_institution', 'stock_items', ['institution_id'], unique=False)
    op.create_index('idx_stock_sku_institution', 'stock_items', ['sku', 'institution_id'], unique=True)
    op.create_index(op.f('ix_stock_items_institution_id'), 'stock_items', ['institution_id'], unique=False)
    op.drop_constraint(op.f('stock_items_family_id_fkey'), 'stock_items', type_='foreignkey')
    op.drop_constraint(op.f('stock_items_institution_id_fkey'), 'stock_items', type_='foreignkey')
    op.create_foreign_key(None, 'stock_items', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stock_items', 'type_stock')
    op.drop_column('stock_items', 'family_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_items', sa.Column('type_stock', postgresql.ENUM('FAMILY', 'INSTITUTION', name='stocktype'), server_default=sa.text("'INSTITUTION'::stocktype"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_items', type_='foreignkey')
    op.create_foreign_key(op.f('stock_items_institution_id_fkey'), 'stock_items', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(op.f('stock_items_family_id_fkey'), 'stock_items', 'families', ['family_id'], ['id'])
    op.drop_index(op.f('ix_stock_items_institution_id'), table_name='stock_items')
    op.drop_index('idx_stock_sku_institution', table_name='stock_items')
    op.drop_index('idx_stock_institution', table_name='stock_items')
    op.create_index(op.f('unique_sku_institution'), 'stock_items', ['sku', 'institution_id'], unique=True)
    op.create_index(op.f('unique_sku_family'), 'stock_items', ['sku', 'family_id'], unique=True)
    op.alter_column('stock_items', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('stock_items', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'stock_history', type_='foreignkey')
    op.create_foreign_key(op.f('stock_history_stock_item_id_fkey'), 'stock_history', 'stock_items', ['stock_item_id'], ['id'])
    op.drop_index(op.f('ix_stock_history_stock_item_id'), table_name='stock_history')
    op.drop_index('idx_stock_history_item', table_name='stock_history')
    op.drop_index('idx_stock_history_created', table_name='stock_history')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_account_id_fkey'), 'profiles', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_cpf'), table_name='profiles')
    op.drop_index('idx_profiles_cpf', table_name='profiles')
    op.drop_index('idx_profiles_account', table_name='profiles')
    op.create_unique_constraint(op.f('profiles_cpf_key'), 'profiles', ['cpf'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('profiles_cpf_idx'), 'profiles', ['cpf'], unique=False)
    op.add_column('institutions', sa.Column('institutions_type', postgresql.ENUM('ONGS', 'CHURCH', name='institutiontype'), autoincrement=False, nullable=False))
    op.add_column('institutions', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('institutions_owner_id_fkey'), 'institutions', 'accounts', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index('idx_institutions_type', table_name='institutions')
    op.drop_index('idx_institutions_name', table_name='institutions')
    op.create_unique_constraint(op.f('institutions_owner_id_key'), 'institutions', ['owner_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('institutions_name_idx'), 'institutions', ['name'], unique=False)
    op.drop_column('institutions', 'institution_type')
    op.add_column('families', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('families_owner_id_fkey'), 'families', 'accounts', ['owner_id'], ['id'])
    op.create_unique_constraint(op.f('families_owner_id_key'), 'families', ['owner_id'], postgresql_nulls_not_distinct=False)
    op.add_column('accounts', sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('login', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('accounts_family_id_fkey'), 'accounts', 'families', ['family_id'], ['id'])
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index('idx_accounts_institution', table_name='accounts')
    op.drop_index('idx_accounts_email', table_name='accounts')
    op.create_unique_constraint(op.f('accounts_login_key'), 'accounts', ['login'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('accounts_login_idx'), 'accounts', ['login'], unique=False)
    op.create_unique_constraint(op.f('accounts_email_key'), 'accounts', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('accounts', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'account_type',
               existing_type=sa.Enum('OWNER', 'DELIVERY_MAN', 'ADMINISTRATIVE', 'ASSISTANT', 'VOLUNTEER', 'UNDEFINED', name='accounttype', native_enum=False),
               type_=postgresql.ENUM('DELIVERY_MAN', 'ADMINISTRATIVE', 'BENEFITED', 'INDEFINED', name='accounttype'),
               existing_nullable=False)
    op.drop_column('accounts', 'password')
    # ### end Alembic commands ###
