"""fix

Revision ID: 5eedcb80c257
Revises: f82a168d6541
Create Date: 2025-09-28 12:11:32.863576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eedcb80c257'
down_revision: Union[str, Sequence[str], None] = 'f82a168d6541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_index('accounts_login_idx', 'accounts', ['login'], unique=False)
    op.create_foreign_key(None, 'accounts', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index('accounts_login_idx', table_name='accounts')
    op.drop_column('accounts', 'family_id')
    # ### end Alembic commands ###
