"""fix

Revision ID: 60c2c66923ac
Revises: 5eedcb80c257
Create Date: 2025-09-28 15:57:30.867618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c2c66923ac'
down_revision: Union[str, Sequence[str], None] = '5eedcb80c257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('accounts_login_idx', 'accounts', ['login'], unique=False)
    op.add_column('families', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_index('profiles_cpf_idx', 'profiles', ['cpf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('profiles_cpf_idx', table_name='profiles')
    op.drop_column('families', 'active')
    # op.drop_index('accounts_login_idx', table_name='accounts')
    # ### end Alembic commands ###
