"""fix

Revision ID: 6a9e11181433
Revises: 050f31188c2a
Create Date: 2025-11-24 13:10:31.849169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9e11181433'
down_revision: Union[str, Sequence[str], None] = '050f31188c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_deliveries', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='situationdelivery', native_enum=False), nullable=False, server_default='PENDING', comment='Situação da entrega'))
    op.create_index(op.f('ix_family_deliveries_status'), 'family_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_deliveries_status'), table_name='family_deliveries')
    op.drop_column('family_deliveries', 'status')
    # ### end Alembic commands ###
