"""add

Revision ID: 6f92f1d90021
Revises: 4b58bb5f04f4
Create Date: 2025-10-31 19:21:27.091007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f92f1d90021'
down_revision: Union[str, Sequence[str], None] = '4b58bb5f04f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_items', sa.Column('sku', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'sku')
    # ### end Alembic commands ###
