"""fix

Revision ID: 806381875674
Revises: 0bd4b223e0b5
Create Date: 2025-11-27 21:22:05.638196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806381875674'
down_revision: Union[str, Sequence[str], None] = '0bd4b223e0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets_institutions',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('basket_type', sa.Enum('P', 'M', 'G', name='baskettype', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baskets_institutions_family_id'), 'baskets_institutions', ['family_id'], unique=False)
    op.create_table('institution_visitations',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('visit_at', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type_of_visit', sa.Enum('ADMISSION', 'READMISSION', 'ROUTINE', name='institutionvisitationtype', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_visitations_account_id'), 'institution_visitations', ['account_id'], unique=False)
    op.create_index(op.f('ix_institution_visitations_institution_id'), 'institution_visitations', ['institution_id'], unique=False)
    op.create_table('institution_visitation_results',
    sa.Column('visitation_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='institutionvisitationresulttype', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['visitation_id'], ['institution_visitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_visitation_results_visitation_id'), 'institution_visitation_results', ['visitation_id'], unique=False)
    op.create_table('products_baskets_institutions',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets_institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_baskets_institutions_basket_id'), 'products_baskets_institutions', ['basket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_baskets_institutions_basket_id'), table_name='products_baskets_institutions')
    op.drop_table('products_baskets_institutions')
    op.drop_index(op.f('ix_institution_visitation_results_visitation_id'), table_name='institution_visitation_results')
    op.drop_table('institution_visitation_results')
    op.drop_index(op.f('ix_institution_visitations_institution_id'), table_name='institution_visitations')
    op.drop_index(op.f('ix_institution_visitations_account_id'), table_name='institution_visitations')
    op.drop_table('institution_visitations')
    op.drop_index(op.f('ix_baskets_institutions_family_id'), table_name='baskets_institutions')
    op.drop_table('baskets_institutions')
    # ### end Alembic commands ###
