"""fix

Revision ID: 823873162b86
Revises: 806381875674
Create Date: 2025-11-28 10:45:37.390156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823873162b86'
down_revision: Union[str, Sequence[str], None] = '806381875674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_baskets_institutions_institution_id'), 'baskets_institutions', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'baskets_institutions', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.add_column('institution_visitations', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_institution_visitations_family_id'), 'institution_visitations', ['family_id'], unique=False)
    op.create_foreign_key(None, 'institution_visitations', 'account_families', ['family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'institution_visitations', type_='foreignkey')
    op.drop_index(op.f('ix_institution_visitations_family_id'), table_name='institution_visitations')
    op.drop_column('institution_visitations', 'family_id')
    op.drop_constraint(None, 'baskets_institutions', type_='foreignkey')
    op.drop_index(op.f('ix_baskets_institutions_institution_id'), table_name='baskets_institutions')
    # ### end Alembic commands ###
