"""fix unique

Revision ID: 827fed87387d
Revises: b59520231c34
Create Date: 2025-11-04 21:16:45.882672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827fed87387d'
down_revision: Union[str, Sequence[str], None] = 'b59520231c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stock_items_sku_key'), 'stock_items', type_='unique')
    op.create_index('unique_sku_family', 'stock_items', ['sku', 'family_id'], unique=True)
    op.create_index('unique_sku_institution', 'stock_items', ['sku', 'institution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_sku_institution', table_name='stock_items')
    op.drop_index('unique_sku_family', table_name='stock_items')
    op.create_unique_constraint(op.f('stock_items_sku_key'), 'stock_items', ['sku'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
