"""id

Revision ID: 83a4aae579a7
Revises: 658b857b8ce5
Create Date: 2025-11-04 20:12:08.130977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a4aae579a7'
down_revision: Union[str, Sequence[str], None] = '658b857b8ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('accounts_login_idx', 'accounts', ['login'], unique=False)
    op.add_column('stock_items', sa.Column('family_id', sa.Integer(), nullable=True))
    op.alter_column('stock_items', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'stock_items', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_items', type_='foreignkey')
    op.alter_column('stock_items', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('stock_items', 'family_id')
    op.drop_index('accounts_login_idx', table_name='accounts')
    # ### end Alembic commands ###
