"""auth persons

Revision ID: 8fdfccce735e
Revises: 00a431cd0669
Create Date: 2025-11-20 10:48:03.540196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdfccce735e'
down_revision: Union[str, Sequence[str], None] = '00a431cd0669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autihorized_persons_families',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome da pessoa autorizada'),
    sa.Column('cpf', sa.String(length=11), nullable=True, comment='CPF da pessoa autorizada'),
    sa.Column('kinship', sa.Enum('SON', 'SPOUSE', 'FATHER', 'MOTHER', 'OTHER', name='degreeofkinship', native_enum=False), nullable=False, comment='Relação com a família'),
    sa.Column('family_id', sa.Integer(), nullable=False, comment='Família à qual a pessoa está autorizada'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authorized_person_cpf', 'autihorized_persons_families', ['cpf'], unique=False)
    op.create_index('idx_authorized_person_family_id', 'autihorized_persons_families', ['family_id'], unique=False)
    op.create_index(op.f('ix_autihorized_persons_families_cpf'), 'autihorized_persons_families', ['cpf'], unique=True)
    op.create_index(op.f('ix_autihorized_persons_families_family_id'), 'autihorized_persons_families', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autihorized_persons_families_family_id'), table_name='autihorized_persons_families')
    op.drop_index(op.f('ix_autihorized_persons_families_cpf'), table_name='autihorized_persons_families')
    op.drop_index('idx_authorized_person_family_id', table_name='autihorized_persons_families')
    op.drop_index('idx_authorized_person_cpf', table_name='autihorized_persons_families')
    op.drop_table('autihorized_persons_families')
    # ### end Alembic commands ###
