"""add stock type

Revision ID: 9952c38e2883
Revises: b6ed09bb1881
Create Date: 2025-10-31 20:32:36.181208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9952c38e2883'
down_revision: Union[str, Sequence[str], None] = 'b6ed09bb1881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    stocktype_enum = sa.Enum('FAMILY', 'INSTITUTION', name='stocktype')
    stocktype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('stock_items', sa.Column('type_stock', stocktype_enum, nullable=False, server_default='INSTITUTION'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'type_stock')
    stocktype_enum = sa.Enum('FAMILY', 'INSTITUTION', name='stocktype')
    stocktype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

