"""refactor

Revision ID: a50adfca45c7
Revises: 58bb34ea4da6
Create Date: 2025-11-08 19:45:34.709035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a50adfca45c7'
down_revision: Union[str, Sequence[str], None] = '58bb34ea4da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_families',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nome do responsável pela família'),
    sa.Column('cpf', sa.String(length=11), nullable=False, comment='CPF do responsável'),
    sa.Column('mobile_phone', sa.String(length=15), nullable=False, comment='Telefone celular para contato'),
    sa.Column('cep', sa.String(length=9), nullable=False, comment='CEP do endereço'),
    sa.Column('rua', sa.String(length=100), nullable=False, comment='Nome da rua'),
    sa.Column('numero', sa.String(length=10), nullable=False, comment='Número do endereço'),
    sa.Column('bairro', sa.String(length=100), nullable=False, comment='Nome do bairro'),
    sa.Column('estado', sa.String(length=2), nullable=False, comment='UF do estado'),
    sa.Column('situation', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='situationtype', native_enum=False), nullable=False, comment='Situação atual da família no programa'),
    sa.Column('renda', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Renda mensal da família'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Observações adicionais sobre a família'),
    sa.Column('institution_id', sa.Integer(), nullable=False, comment='Instituição responsável pela família'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('length(cpf) = 11', name='check_cpf_length'),
    sa.CheckConstraint('length(estado) = 2', name='check_estado_length'),
    sa.CheckConstraint('renda >= 0', name='check_renda_positive'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_cpf', 'account_families', ['cpf'], unique=False)
    op.create_index('idx_family_institution', 'account_families', ['institution_id'], unique=False)
    op.create_index('idx_family_name', 'account_families', ['name'], unique=False)
    op.create_index('idx_family_situation', 'account_families', ['situation'], unique=False)
    op.create_index(op.f('ix_account_families_cpf'), 'account_families', ['cpf'], unique=True)
    op.create_index(op.f('ix_account_families_institution_id'), 'account_families', ['institution_id'], unique=False)
    op.create_index(op.f('ix_account_families_situation'), 'account_families', ['situation'], unique=False)
    op.create_table('doc_families',
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='Tipo do documento (ex: RG, comprovante de residência, etc.)'),
    sa.Column('doc_file', sa.LargeBinary(), nullable=False, comment='Arquivo do documento em formato binário'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='Nome original do arquivo'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='Tipo MIME do arquivo'),
    sa.Column('family_id', sa.Integer(), nullable=False, comment='Família à qual o documento pertence'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_family_id', 'doc_families', ['family_id'], unique=False)
    op.create_index('idx_doc_type', 'doc_families', ['doc_type'], unique=False)
    op.create_index(op.f('ix_doc_families_doc_type'), 'doc_families', ['doc_type'], unique=False)
    op.create_index(op.f('ix_doc_families_family_id'), 'doc_families', ['family_id'], unique=False)
    
    # Drop visitfamilies first (has FK to families)
    op.drop_table('visitfamilies')
    # Then drop families
    op.drop_table('families')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitfamilies',
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('visitfamilies_family_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visitfamilies_pkey'))
    )
    op.create_table('families',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('family_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('complement', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('proof_address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('monthly_income', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('situation_type', postgresql.ENUM('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='situationtype'), autoincrement=False, nullable=False),
    sa.Column('proof_address_verificed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('membership_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('benefit_expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('family_size > 0', name=op.f('family_size_positive')),
    sa.CheckConstraint('monthly_income >= 0::numeric', name=op.f('monthly_income_positive')),
    sa.ForeignKeyConstraint(['membership_id'], ['institutions.id'], name=op.f('families_membership_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('families_pkey'))
    )
    op.drop_index(op.f('ix_doc_families_family_id'), table_name='doc_families')
    op.drop_index(op.f('ix_doc_families_doc_type'), table_name='doc_families')
    op.drop_index('idx_doc_type', table_name='doc_families')
    op.drop_index('idx_doc_family_id', table_name='doc_families')
    op.drop_table('doc_families')
    op.drop_index(op.f('ix_account_families_situation'), table_name='account_families')
    op.drop_index(op.f('ix_account_families_institution_id'), table_name='account_families')
    op.drop_index(op.f('ix_account_families_cpf'), table_name='account_families')
    op.drop_index('idx_family_situation', table_name='account_families')
    op.drop_index('idx_family_name', table_name='account_families')
    op.drop_index('idx_family_institution', table_name='account_families')
    op.drop_index('idx_family_cpf', table_name='account_families')
    op.drop_table('account_families')
    # ### end Alembic commands ###
