"""add

Revision ID: b6ed09bb1881
Revises: 6f92f1d90021
Create Date: 2025-10-31 19:27:36.246145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ed09bb1881'
down_revision: Union[str, Sequence[str], None] = '6f92f1d90021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stock_items', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_items', type_='unique')
    # ### end Alembic commands ###
