"""fix

Revision ID: c8e267be6626
Revises: b240a7b19535
Create Date: 2025-09-21 16:16:37.837096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e267be6626'
down_revision: Union[str, Sequence[str], None] = 'b240a7b19535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_authorized_accounts', sa.Column('login', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_authorized_accounts', 'login')
    # ### end Alembic commands ###
