"""fix

Revision ID: f05197d68dbd
Revises: 823873162b86
Create Date: 2025-11-29 18:10:27.575541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05197d68dbd'
down_revision: Union[str, Sequence[str], None] = '823873162b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_basket_families',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('basket_type', sa.Enum('P', 'M', 'G', name='baskettype', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['account_families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_basket_families_family_id'), 'institution_basket_families', ['family_id'], unique=False)
    op.create_index(op.f('ix_institution_basket_families_institution_id'), 'institution_basket_families', ['institution_id'], unique=False)
    op.create_table('institution_basket_family_lines',
    sa.Column('basket_family_id', sa.Integer(), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['basket_family_id'], ['institution_basket_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_basket_family_lines_basket_family_id'), 'institution_basket_family_lines', ['basket_family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institution_basket_family_lines_basket_family_id'), table_name='institution_basket_family_lines')
    op.drop_table('institution_basket_family_lines')
    op.drop_index(op.f('ix_institution_basket_families_institution_id'), table_name='institution_basket_families')
    op.drop_index(op.f('ix_institution_basket_families_family_id'), table_name='institution_basket_families')
    op.drop_table('institution_basket_families')
    # ### end Alembic commands ###
