"""add benefit

Revision ID: f877de88393f
Revises: 1bf5bc9f755a
Create Date: 2025-10-14 20:04:29.466803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f877de88393f'
down_revision: Union[str, Sequence[str], None] = '1bf5bc9f755a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('benefit_expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'benefit_expiration_date')
    # ### end Alembic commands ###
